# Generated by Django 3.1.7 on 2021-03-28 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nominal_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ip_address', models.CharField(max_length=30)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('bank', models.CharField(max_length=100)),
                ('client', models.CharField(max_length=100)),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.loan')),
            ],
        ),
    ]
