# Generated by Django 3.1.7 on 2021-03-30 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20210329_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='interest_type',
            field=models.IntegerField(choices=[(1, 'Simple'), (2, 'Compound')], default=1),
        ),
    ]
